### ISSUE TITLE
[FEATURE] Allow to limit owners and admins of team depend on team rank

### ISSUE THREAD

**Issue by GuazP** [booksaw/BetterTeams#156]
**Is your feature request related to a problem? Please describe.**
I would like to limit how many owners or admins could team have along max members per rank of team.

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
Not applies

**Additional context**
Not applies

**Comment by megargayu** [comment]
So, this is how I would visualize how this would work (in `config.yml`):
```yaml
# Used to limit the number of each rank allowed in teams
# - If this is set as 0 or a negative number the rank would be allowed infinitely
# - If a rank is not set, it is allowed infinitely 
#
# Possible values: [Rank, followed by an integer]
maxTeamRanks:
   OWNER: 2
   ADMIN: 2
   DEFAULT: 0
```

This example would make every team have a max of 2 owners, 2 admins, and infinite members (set within the limits of [`maxTeamLength`](https://github.com/booksaw/BetterTeams/blob/master/config.yml#L61-L65)).

One problem would be with [`singleOwner`](https://github.com/booksaw/BetterTeams/blob/master/config.yml#L194-L200) - this probably would have to be removed. However, what would happen to `/team setowner` then? I think that `/team setowner` should be deleted in favor of putting more logic into `/team promote`, but that's up to debate.

Another point would be with [`levels`](https://github.com/booksaw/BetterTeams/blob/master/config.yml#L232-L273) - should we add `maxTeamRanks` to it?

Also want to point out that this will make interesting behavior with [`maxTeamLength`](https://github.com/booksaw/BetterTeams/blob/master/config.yml#L61-L65) and that code would probably need to be refactored.

@booksaw what do you think?
