### ISSUE TITLE
[FEATURE] Ingame description what actually team rank gives

### ISSUE THREAD

**Issue by GuazP** [booksaw/BetterTeams#215]
**Is your feature request related to a problem? Please describe.**
I looked for in-game info what current team level gives for team, and what next team level could give for team. And generally I tried to find with `/team help`, but I didn'f found something like this. `/team info` and `/team rank` doesn't show such things either.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I mean info what actually team level gives, for example, how many chests you can have, how many warps you can set, how many people you can invite.
Example output of /team rank (or other command) I'm looking to:
```
Team rank: 5 ($ 10800 needed for next rankup)
Max team members: 5 (9 at next rank)
Max team chests: 1 (1 at next rank)
Max team warps: 3 (4 at next rank)
...
```
And so on, if more parameters are possible to set to upgrade with team rankup :)

Currently `/team rank` gives only first line of this example.

**Additional context**
It could be like 'wildcard'/`free to define` per team rank, where designer of team ranks could put whatever he likes into `/team rank`
Because for now, there is no in-game way to obtain info what team provide for you and what gives next rank...
For example:
```
levels:
  l1:
    teamLimit: 3
    maxChests: 0
    maxWarps: 1
    rankLore:
      - "&6Max team members:&3 3&7 (5 at next rank)"
      - "&6Max team chests:&3 0&7 (1 at next rank)"
      - "&6Max team warps:&3 1 &7(2 at next rank)"
      - "&6Daily team minor owner reward!"
  l2:
    teamLimit: 5
    maxChests: 1
    price: 1000m
    maxWarps: 2
    rankLore:
      ...
```
It would cover almost any needed additional description despite features you'll add in future :)
Just a free idea of 'end user usage', use it or drop it however you like ^^
