### ISSUE TITLE
[BUG] noTeam placeholder not displaying correctly

### ISSUE THREAD

**Issue by booksaw** [booksaw/BetterTeams#401]
### What is the bug?

PAPI placeholders displayed incorrectly

Cannot currently figure out how to reproduce. Need more guidance

### Expected Behaviour

![image](https://user-images.githubusercontent.com/13976636/215866503-6299ebca-0320-4504-bf93-86db16e27ff4.png)

### How to Reproduce

set placeholder portion of message.yml to
```yaml
placeholder:
  noTeam: ''
  noDescription: ''
  money: '%s'
  owner: Owner
  admin: Admin
  default: Default
  name: '&7[%s&7]'
  tag: '&7[%s&7]'
  displayname: '%s'
  inteam: 'true'
  notinteam: 'false'
  noTitle: ''
```

### Output of /teama version

![image](https://user-images.githubusercontent.com/13976636/215866644-a5aedada-37b4-4a8b-9474-d169114db6b4.png)
