### ISSUE TITLE
[FEATURE] RAW Invitations

### ISSUE THREAD

**Issue by Dharuzz** [booksaw/BetterTeams#423]
### What is the feature request for?

Hi!

Please make it so that the `invite.invite` message is a RAW Message so it can be clicked on and players can easily join someone's team by clicking on their invitations.
```yaml
invite:
  invite: '&dYou have been invited to join team&f %s &ddo &f/team join <team> &d to join
  the team'
```

### Feature requests are not going to be implemented by booksaw, instead you will have to find another developer to make a pull request to implement the feature.

- [X] I understand
