### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by poyrats** [booksaw/BetterTeams#426]
### What is the bug?

I set the create cost "100.000" but i can created team with 0 money.

### Expected Behaviour

fix it

### How to Reproduce

set a create cost
create team with 0 money

### Error message

no message

### Output of /teama version

4.6.2

**Comment by booksaw** [comment]
@poyrats 
Please see the below screenshot, I have been unable to reproduce the issue as with the config provided in this message, the team cost has been taken from the team correctly, please advice on specific plugins etc. which may be causing the problem if there are any differences from my example shown below.

```yaml
cooldowns: 
#- 'home:60'
## The line above will add a 60 second cooldown to the command /team home

# COSTS - Make take a certain amount of money from the players balance when they run a command
# To bypass the cost have the permission node betterteams.cost.bypass
costs:
- 'create:1000'

# This option determines if the command cost is taken from the team balance first or the individual player
#
# Possible values: [true, false]
costFromTeam: true
```

![image](https://user-images.githubusercontent.com/13976636/227728451-045fa20d-10fa-4941-94b3-8ae1061f729b.png)
