### ISSUE TITLE
[BUG] endCommands leveling-up bug.

### ISSUE THREAD

**Issue by cuplad** [booksaw/BetterTeams#433]
### What is the bug?

The endCommands is supposed to run commands whenever the team that is from the level the commands were typed on. Levels-up as i understand it. Though that didn't happen as i was trying to make the team's color change depending on the level the team's on. So i made it that when the team's on level one. The endCommands for it is:
- teamadmin color %team% (any team color)
And that format continues with all of the levels with different colors. But no matter how many times or from what level you level up. Your team's color stays as it is. I'll attach the config's file so it can be easier to read if my rusty explanation didn't cut it out :-)
(the file's gonna be in as a txt file just for uploading purposes)

[config.txt](https://github.com/booksaw/BetterTeams/files/11136904/config.txt)

### Expected Behaviour

Look into the bug. and fix it 0-0

### How to Reproduce

Just replace the levels section with this:
```yaml
levels:
  l1:
    teamLimit: 5
    maxChests: 0
    maxWarps: 1
    maxBal: 10000
    maxAdmins: 3
    maxOwners: 1
    rankLore:
    - '&7Team Level - &8Rookie'
    endCommands:
    - teamadmin color %team% green
  l2:
    price: 5000m
    teamLimit: 7
    maxChests: 0
    maxWarps: 2
    maxBal: 25000
    maxAdmins: 3
    maxOwners: 1
    rankLore:
    - '&7Team Level - &aNovice'
    endCommands:
    - teamadmin color %team% blue
  l3:
    price: 15000m
    teamLimit: 10
    maxChests: 1
    maxWarps: 3
    maxBal: 50000
    maxAdmins: 4
    maxOwners: 1
    rankLore:
    - '&7Team Level - &9Apprentice'
    endCommands:
    - teamadmin color %team% cyan
  l4:
    price: 50000m
    teamLimit: 12
    maxChests: 2
    maxWarps: 4
    maxBal: 150000
    maxAdmins: 5
    maxOwners: 2
    rankLore:
    - '&7Team Level - &3Advanced'
    endCommands:
    - teamadmin color %team% pink
  l5:
    price: 100000m
    teamLimit: 15
    maxChests: 3
    maxWarps: 5
    maxBal: 250000
    maxAdmins: 7
    maxOwners: 3
    rankLore:
    - '&7Team Level - &dMaster'
    endCommands:
    - teamadmin color %team% green
  l6:
    price: 200000m
    teamLimit: 20
    maxChests: 4
    maxWarps: 6
    maxBal: 350000
    maxAdmins: 10
    maxOwners: 4
    rankLore:
    - '&7Team Level - &5GrandMaster'
```
### Error message

No error messages.

### Output of /teama version

[Server] [INFO] [BetterTeams] Storage Method: 
com.booksaw.betterTeams.team.storage.storageManager.SeparatedYamlStorageManager
[Server] [INFO] [BetterTeams] Minecraft Version: git-Paper-307 (MC: 1.19.2)
[Server] [INFO] [BetterTeams] Language Selected: messages
[Server] [INFO] [BetterTeams] Current plugin version: 4.6.4

### Additional Information

I've tested with other teamadmin commands and it doesn't seem to work either.
