### ISSUE TITLE
[BUG] Got kicked out of team by putting duration 3 fireworks in team echest

### ISSUE THREAD

**Issue by Blastboys** [booksaw/BetterTeams#614]
### What is the bug?

My teammate put duration 3 fireworks in Team Echest, and we've got kicked out of our team. We can't join the team using /teamadmin join [team] [username] and we CAN'T create another team using /team create

### Expected Behaviour

Not kick me out of my team and allow me to atleast create a new team

### How to Reproduce

I wasn't online when this happened, I just rejoined and saw that I wasn't in my team
According to my friend, this is what happened.
He used /team echest
He put Duration 3 Fireworks in team echest
He logged off to eat dinner
When he logged back on the saw that we got kicked out of our team

### Error message

[19:33:34] [Server thread/INFO]: octave1 issued server command: /teamadmin join supremesigma octave1
[19:33:34] [Craft Scheduler Thread - 19/ERROR]: Something went wrong while executing the command, please report this https://github.com/booksaw/BetterTeams/issues/new/choose
[19:33:34] [Craft Scheduler Thread - 19/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.effects" is null
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftMetaFirework.applyToItem(CraftMetaFirework.java:189)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:632)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at org.bukkit.craftbukkit.v1_20_R4.inventory.CraftInventory.setItem(CraftInventory.java:101)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.team.storage.team.YamlTeamStorage.getEchestContents(YamlTeamStorage.java:96)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.team.EChestComponent.load(EChestComponent.java:29)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.Team.<init>(Team.java:335)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:74)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.team.TeamManager.getTeam(TeamManager.java:122)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.Team.getTeam(Team.java:94)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.commands.teama.JoinTeama.onCommand(JoinTeama.java:24)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.commands.ParentCommand.onCommand(ParentCommand.java:135)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.BooksawCommand.runExecution(BooksawCommand.java:73)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at com.booksaw.betterTeams.BooksawCommand.lambda$execute$0(BooksawCommand.java:60)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftTask.run(CraftTask.java:82)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:33:34] [Craft Scheduler Thread - 19/WARN]:  at java.base/java.lang.Thread.run(Unknown Source)

### Output of /teama version

![image](https://github.com/booksaw/BetterTeams/assets/66127643/2e971783-d402-4a51-9506-2bfa56cc2010)

### Additional Information

Happened right after my teammate put duration 3 fireworks in team echest, cannot do /team create anymore and cannot do /teamadmin disband [team]

**Comment by booksaw** [comment]
```yaml 
name: NAME
description: ''
open: false
pvp: false
color: c
chests: []
players:
- AAAA:OWNER
level: 1
tag: ''
echest:
  '4':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: GOLD_NUGGET
    amount: 3
  '5':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: EMERALD
    amount: 7
  '1':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: QUARTZ
    amount: 50
  '0':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: COBWEB
    amount: 64
  '7':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
      custom-effects: []
  '8':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
      custom-effects: []
  '2':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: FEATHER
    amount: 12
  '3':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: GHAST_SPAWN_EGG
    amount: 2
    meta:
      ==: ItemMeta
      meta-type: SPAWN_EGG
      display-name: '{"text":"","extra":[{"text":"SafariNet ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false},{"text":"(","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"dark_aqua","bold":false},{"text":"Single-Use","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false},{"text":")","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"dark_aqua","bold":false}]}'
      lore:
      - '{"text":"","extra":["Right click on an entity"]}'
      - '{"text":"","extra":["to catch it!"]}'
  '24':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: FIREWORK_ROCKET
    amount: 64
    meta:
      ==: ItemMeta
      meta-type: FIREWORK
      power: 3
  '25':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: FIREWORK_ROCKET
    amount: 64
    meta:
      ==: ItemMeta
      meta-type: FIREWORK
      power: 3
  '26':
    ==: org.bukkit.inventory.ItemStack
    v: 3839
    type: FIREWORK_ROCKET
    amount: 64
    meta:
      ==: ItemMeta
      meta-type: FIREWORK
      power: 3
```
